spring:
  application:
    name: SpringSecurity
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: uu
    password: 0123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

