spring:
  application:
    name: SpringSecurity
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: hyo
    password: 0729
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

